# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c96bcb9c-4ec6-418b-aff3-2517c7fdab38";
      fsType = "xfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/73303904-3f71-4474-bee6-633ae7abd39e";
      fsType = "xfs";
    };
  fileSystems."/home/dahai003/backup" =
    {
    device = "/dev/disk/by-label/backup";
    fsType = "xfs";
    };
  fileSystems."/home/dahai003/Data" =
    {
    device = "/dev/disk/by-label/data";
    fsType = "xfs";
    };
  fileSystems."/home/dahai003/LLMs" =
    {
    device = "/dev/disk/by-label/LLMs";
    fsType = "xfs";
    };
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/22C1-A08A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/bin" =
    { device = "/usr/bin";
      fsType = "none";
      options = [ "bind" ];
    };

  swapDevices = [
    {
    device = "/dev/disk/by-uuid/9a0e42b7-b8ec-4bdd-b960-927fa1da7640";  # Swap partition (adjust as needed)
   }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0f4u1u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
